"""update start_date to start_datetime rename 

Revision ID: 03ca7c542bee
Revises: 91dc204f7d14
Create Date: 2024-07-22 21:11:07.702439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03ca7c542bee'
down_revision: Union[str, None] = '91dc204f7d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('start_datetime', sa.DateTime(), nullable=False))
    op.add_column('booking', sa.Column('end_datetime', sa.DateTime(), nullable=False))
    op.drop_column('booking', 'end_date')
    op.drop_column('booking', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('booking', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('booking', 'end_datetime')
    op.drop_column('booking', 'start_datetime')
    # ### end Alembic commands ###
