"""add all cascade delete books

Revision ID: 10ec5ab0b5fa
Revises: 03ca7c542bee
Create Date: 2024-07-23 15:26:36.035158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ec5ab0b5fa'
down_revision: Union[str, None] = '03ca7c542bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
