"""add unique constarain to start and end date to booking

Revision ID: 18b09cf0f4e6
Revises: 9763558c40c5
Create Date: 2024-07-22 10:58:34.964377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b09cf0f4e6'
down_revision: Union[str, None] = '9763558c40c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_booking_end_date', 'booking', ['book_id', 'end_date'])
    op.create_unique_constraint('unique_booking_start_date', 'booking', ['book_id', 'start_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_booking_start_date', 'booking', type_='unique')
    op.drop_constraint('unique_booking_end_date', 'booking', type_='unique')
    # ### end Alembic commands ###
