"""booking models update

Revision ID: 9763558c40c5
Revises: 21d048928757
Create Date: 2024-07-22 10:41:40.285145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9763558c40c5'
down_revision: Union[str, None] = '21d048928757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('booking', sa.Column('end_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'end_date')
    op.drop_column('booking', 'start_date')
    # ### end Alembic commands ###
