"""Added BookingStatus enum

Revision ID: d471c2cec420
Revises: 18b09cf0f4e6
Create Date: 2024-07-22 11:43:13.304082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd471c2cec420'
down_revision: Union[str, None] = '18b09cf0f4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


bookingstatus_enum = postgresql.ENUM('active', 'returned', 'cancelled', name='bookingstatus')


def upgrade() -> None:
    # Create the enum type
    bookingstatus_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('status', bookingstatus_enum, nullable=True, server_default='active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'status')
    # ### end Alembic commands ###

    # Drop the enum type
    bookingstatus_enum.drop(op.get_bind())
