"""delete constarin to booking

Revision ID: e6bb479ca63a
Revises: d471c2cec420
Create Date: 2024-07-22 20:57:38.509068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6bb479ca63a'
down_revision: Union[str, None] = 'd471c2cec420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'RETURNED', 'CANCELLED', name='bookingstatus'),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::bookingstatus"))
    op.drop_constraint('unique_booking_end_date', 'booking', type_='unique')
    op.drop_constraint('unique_booking_start_date', 'booking', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_booking_start_date', 'booking', ['book_id', 'start_date'])
    op.create_unique_constraint('unique_booking_end_date', 'booking', ['book_id', 'end_date'])
    op.alter_column('booking', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'RETURNED', 'CANCELLED', name='bookingstatus'),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::bookingstatus"))
    # ### end Alembic commands ###
